# Generated by Django 5.1.1 on 2024-10-16 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.CharField(max_length=8)),
                ('card_nr', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('work_type', models.CharField(max_length=255)),
                ('act', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=4)),
                ('teta_nr', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('id_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='main.card')),
                ('id_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='main.worker')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='id_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='main.worker'),
        ),
    ]
